### ISSUE TITLE
Not exactly an issue

### ISSUE THREAD

**Issue by Sharahs** [azakhi/GDModdingTool#4]
Hello,
first of all, thanks for the mod! Without any knowledge I could manage to pull it off to modify my game.

I wanted to ask if its possible to add a way to change movementspeed in the config.txt file or would it be the best idea to find a movementspeed mod and try to add it somehow?

Thank you!

**Comment by azakhi** [comment]
Hello,
I remember looking into modifying character speed but not adding it for some reason. I can't remember why I didn't add it at the time. If you can find out how it is done, I can help you regarding how to combine it with this tool but can't help much without knowing what exactly needs to be changed.

**Comment by Sharahs** [comment]
Thanks for your reply!

I think my knowledge doesn't go far enough to know what it exactly is that affects speed.

There is a mod which does some different stuff including movement speed:
https://forums.crateentertainment.com/t/mod-mob-density-increased/49606

Does this help or do you need some kind of file or so?

**Comment by azakhi** [comment]
Hello, new update for v1.2 added player run speed adjustments as well.
