### ISSUE TITLE
Hi, Any chance to update for version 1.2.0.0?

### ISSUE THREAD

**Issue by ParanoiaIsGreat** [azakhi/GDModdingTool#5]
![image](https://github.com/azakhi/GDModdingTool/assets/10475153/c3676ddc-9e06-4543-ab09-9901515d0fed)

**Comment by azakhi** [comment]
Hello, I am planning to update the tool for 1.2 but Stasher was created by another mod developer and I included them with their permission. I will check if they updated or if there are alternatives.

**Comment by ParanoiaIsGreat** [comment]
> 

Thank you so much! That's all I want.

**Comment by azakhi** [comment]
Hello, tool is updated for v1.2
