### ISSUE TITLE
Some wrong with AdjustSpecificLootAmount

### ISSUE THREAD

**Issue by ParanoiaIsGreat** [azakhi/GDModdingTool#6]
Thanks for the update! 
It makes me feel a little embarrassed, as if I'm the only one using it. Others just too shy. 
:) 

I got something wrong with AdjustSpecificLootAmount.
When set it to TRUE, I always get a ERROR.
Tried multiple times with different settings, and still ERROR.
The only way is set it to FALSE.
[Logs_26.11.23_15.15.16.txt](https://github.com/azakhi/GDModdingTool/files/13466169/Logs_26.11.23_15.15.16.txt)
[Logs_26.11.23_15.16.42.txt](https://github.com/azakhi/GDModdingTool/files/13466170/Logs_26.11.23_15.16.42.txt)
[Logs_26.11.23_15.18.15.txt](https://github.com/azakhi/GDModdingTool/files/13466171/Logs_26.11.23_15.18.15.txt)
[Logs_26.11.23_15.19.41.txt](https://github.com/azakhi/GDModdingTool/files/13466172/Logs_26.11.23_15.19.41.txt)
[Logs_26.11.23_15.21.47.txt](https://github.com/azakhi/GDModdingTool/files/13466173/Logs_26.11.23_15.21.47.txt)

**Comment by ParanoiaIsGreat** [comment]
Don't know why but this works fine now...
`AdjustSpecificLootAmount 200 Amulet,Armor,Belt,Blueprint,Component,Medal,Potion,Quest,Relic,Ring,Shield,Weapon Legendary True`
`AdjustSpecificLootAmount 20 Amulet,Armor,Belt,Blueprint,Component,Medal,Potion,Quest,Relic,Ring,Shield,Weapon Epic True`

**Comment by azakhi** [comment]
Hello, these are the error lines from the logs:

> ERROR: Invalid parameters: AdjustSpecificLootAmount 200 Amulet,Armor,Belt,Blueprint,Component,Medal,Quest,Ring,Shield,Weapon Legendary Ture
ERROR: Invalid parameters: AdjustSpecificLootAmount 20 Amulet,Armor,Belt,Blueprint,Component,Medal,Quest,Ring,Shield,Weapon Epic Ture

It says that you used `Ture` but it should be `True`. Could you please check if there is a typo?

**Comment by ParanoiaIsGreat** [comment]
Oh my bad... Sry about that...
It works fine.

**Comment by azakhi** [comment]
No problem
